name: LCK Roster Sync

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch: 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 

      - name: Install dependencies
        run: npm install axios @supabase/supabase-js

      - name: Run sync script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          PANDASCORE_API_KEY: "DHvxd5PMWZiFZvs3WnQhEZIXHAUKzpOc-YgNQrrfjByFAXpakF4"
        run: node scripts/sync-roster.js






